version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 22
   
    commands:
        # install npm
        - npm install
        - npm install react-scripts --save
       
  build:
    commands:
        # run build script
        - npm run build
     
artifacts:
  # include all files required to run the application
  files:
    - public/**/*
    - src/**/*
    - package.json
    - appspec.yml
    - scripts/**/*